name: Daily Update

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '30 10 * * 1,3,5,6'


jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'


    - name: Install dependencies
      run: |
        pip install requests tqdm aiohttp

    - name: Extract config value
      id: extract_var
      run: |
        IS_STABLE=$(grep 'is_stability_test' ./function/config.py | awk -F= '{print $2}' | tr -d ' ')
        echo "is_stability_test=${IS_STABLE}" >> $GITHUB_OUTPUT

    - name: Install FFmpeg
      if: ${{ steps.extract_var.outputs.is_stability_test == '1' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Run Python script
      run: python function/main.py

    - name: List directory structure
      run: |
        ls -lR

    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        if ! git diff --staged --quiet; then
          git commit -m "Auto-update"
          git push
        fi


    env:
      TZ: Asia/Shanghai
